device:
  use_cuda: true
g: 1.271e8
rho: 1000
mu: 0.001
input_vars:
- precip
- et
- H_bucket
- rA_spigot
- rH_spigot
- soil_depth
model:
  batch_size: 256
  hidden_state_size: 27
  input_size: 9
  learning_rate:
    gamma: 0.9
    start: 0.1
    step_size: 2
  num_classes: 2
  num_epochs: 8
  seq_length: 336
output_vars:
- q_total
- q_spigot
- q_overflow
synthetic_data:
  test:
    bucket_attributes:
      A_bucket:
      - 1e3
      - 2e3
      rA_spigot:
      - 0.15
      - 0.16
      ET_parameter:
      - 2.2447
      - 9.9807e-5
      - 0.0016
      H_bucket:
      - 0.19
      - 0.21
      rH_spigot:
      - 0.15
      - 0.16
      K_infiltration:
      - -13.8857
      - 1.1835
      soil_depth:
      - 0.9
      - 1.1
    n_buckets: 2
    noise:
      et: 0.05
      head: 0.05
      pet: 0.05
      q: 0.05
    num_records: 4360
    threshold_precip: 0.01
    max_precip: 0.25
    rain_params:
      Heavy:
      - 0.2341
      - 0.0101
      - 0.009250
      Light:
      - 0.0008108
      - 0.0009759
    rain_probability:
      Heavy:
      - 0.45
      - 0.46
      Light:
      - 0.55
      - 0.56
      None:
      - 0.45
      - 0.46
  train:
    bucket_attributes:
      A_bucket:
      - 1e3
      - 2e3
      rA_spigot:
      - 0.15
      - 0.16
      ET_parameter:
      - 2.2447
      - 9.9807e-5
      - 0.0016
      H_bucket:
      - 0.19
      - 0.21
      rH_spigot:
      - 0.15
      - 0.16
      K_infiltration:
      - -13.8857
      - 1.1835
      soil_depth:
      - 0.9
      - 1.1
    n_buckets: 100
    noise:
      et: 0.05
      head: 0.05
      pet: 0.05
      q: 0.05
    num_records: 4360
    threshold_precip: 0.01
    max_precip: 0.25
    rain_params:
      Heavy:
      - 0.2341
      - 0.0101
      - 0.009250
      Light:
      - 0.0008108
      - 0.0009759
    rain_probability:
      Heavy:
      - 0.45
      - 0.46
      Light:
      - 0.55
      - 0.56
      None:
      - 0.45
      - 0.46
  val:
    bucket_attributes:
      A_bucket:
      - 1e3
      - 2e3
      rA_spigot:
      - 0.15
      - 0.16
      ET_parameter:
      - 2.2447
      - 9.9807e-5
      - 0.0016
      H_bucket:
      - 0.19
      - 0.21
      rH_spigot:
      - 0.15
      - 0.16
      K_infiltration:
      - -13.8857
      - 1.1835
      soil_depth:
      - 0.9
      - 1.1
    n_buckets: 16
    noise:
      et: 0.05
      head: 0.05
      pet: 0.05
      q: 0.05
    num_records: 4360
    threshold_precip: 0.01
    max_precip: 0.25
    rain_params:
      Heavy:
      - 0.2341
      - 0.0101
      - 0.009250
      Light:
      - 0.0008108
      - 0.0009759
    rain_probability:
      Heavy:
      - 0.45
      - 0.46
      Light:
      - 0.55
      - 0.56
      None:
      - 0.45
      - 0.46
time_step: 1
